# Gitleaks configuration for Cloud Docs
# Prevents accidental commits of secrets

title = "Cloud Docs Gitleaks Config"

# Allow examples and documentation with obvious placeholders
[allowlist]
description = "Allowlist for Cloud Docs"

# Common safe patterns
paths = [
    ".env.example",
    "**/*.md",  # Documentation often has examples
    "**/testdata/**",
]

# Safe example values
regexes = [
    '''your-[a-zA-Z-]+-here''',
    '''replace-with-[a-zA-Z-]+''',
    '''example\.com''',
    '''localhost''',
    '''TOKEN_PLACEHOLDER''',
    '''your-token-secret''',
    '''your-bucket-name''',
    '''dev-secret''',
    '''test-secret''',
]

# Custom rules for this project
[[rules]]
id = "cloud-docs-token-secret"
description = "Hardcoded TOKEN_SECRET value (long base64)"
# Look for TOKEN_SECRET with a long base64 string (32+ chars)
regex = '''TOKEN_SECRET\s*[:=]\s*["'][A-Za-z0-9+/=]{32,}["']'''
tags = ["secret", "cloud-docs"]

[[rules]]
id = "gcp-service-account-key"
description = "GCP Service Account JSON key"
regex = '''"private_key"\s*:\s*"-----BEGIN'''
tags = ["gcp", "key"]

# Note: Removed high-entropy rule as it may cause false positives
# Rely on default Gitleaks rules instead

# Extend default rules
[extend]
# Use Gitleaks default rules as base
useDefault = true